name: Build LisaEm on Windows
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Avoid \r\n line endings
      - run: git config --global core.autocrlf input

      # Checks-out my repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs the latest Cygwin with default packages
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          # Provide a space-separated or comma-separated list of packages to install
          packages: mingw64-x86_64-gcc-core mingw64-x86_64-gcc-debug-info mingw64-x86_64-gcc-g++ mingw64-x86_64-gcc-objc gcc-core gcc-g++ make

      # Example step to verify the installation by running a Cygwin command
      - name: Run a command in Cygwin
        shell: bash --login --norc -eo pipefail {0}
        run: echo "Cygwin is installed!"

      - name: Run a command in Cygwin
        shell: bash --login --norc -eo pipefail {0}
        run: cygcheck -c cygwin

      - name: Run a command in Cygwin
        shell: bash --login --norc -eo pipefail {0}
        run: ls -la /cygdrive

      - name: Run a command in Cygwin 4
        shell: bash --login --norc -eo pipefail {0}
        run: ls -la "$(cygpath '${{ github.workspace }}')"

      - name: Run a command in Cygwin
        shell: bash --login --norc -eo pipefail {0}
        run: cd "$(cygpath '${{ github.workspace }}')/scripts" && ./build-wx3.2.7-cygwin-windows.sh
        
      
