name: Build LisaEm on Windows
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Checks-out my repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs the latest Cygwin with default packages
      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@master

      # Example step to verify the installation by running a Cygwin command
      - name: Run a command in Cygwin
        shell: C:\cygwin64\bin\bash.exe --login --norc -eo pipefail {0}
        run: |
          echo "Cygwin is installed!"
          uname -a
